In [1]:
import numpy as np

x=np.array([3,1,'2'])
print(x)
print(type(x))

['3' '1' '2']
<class 'numpy.ndarray'>


In [2]:
c=[[1],[1,2]]
print(c)

[[1], [1, 2]]


In [3]:
# 안 됨
np.array([[1],[1,2]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [73]:
d=np.array([[1,23,30],[1,2,-1]])

In [ ]:
for x,y in d:
    print(x,y)

In [ ]:
# 명령어 실행 단어
%(ex. pip install numpy)

In [69]:
a=np.array([1,2,5])
b=np.array([1,4,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

print(b/2.0)

[ 2  6 11]
[ 0 -2 -1]
[ 1  8 30]
[1.         0.5        0.83333333]
[0.5 2.  3. ]


In [49]:
a=np.array(['1','2'])
b=np.array(['1','4'])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> None

In [79]:
print(a.shape)
print(a.dtype)
print(d.dtype)
print(d.shape)
print(d.ndim)

(3,)
int32
int32
(2, 3)
2


In [87]:
e=np.array([[1,2],[3,4],[5,6]])
print(e.ndim)
print(e.shape)

2
(3, 2)


In [91]:
e=np.array([[[1,2],[2,3]],[[3,5],[4,5]],[[5,5],[6,7]]])
print(e.ndim)
print(e.shape)

3
(3, 2, 2)


In [105]:
# 내적
np.dot(a,b)
print(np.dot([1,2],[3,4]))
print(np.dot([[1,2],[3,4]],[[3,4],[5,6]]))

11
[[13 16]
 [29 36]]


In [125]:
a=np.array([[1,2,5],[4,5,6]])
b=np.array([[1,4],[1,4],[1,4]])
print(np.matmul(a,b))

[[ 8 32]
 [15 60]]


In [133]:
a.flatten()

array([1, 2, 5, 4, 5, 6])

In [145]:
print(a)
print(a.ndim)

[[1 2 5]
 [4 5 6]]
2


In [155]:
print(a)
print()
print(a.reshape(3,2))
print()
print(a.reshape(6,1))

[[1 2 5]
 [4 5 6]]

[[1 2]
 [5 4]
 [5 6]]

[[1]
 [2]
 [5]
 [4]
 [5]
 [6]]


In [175]:
print(np.random.randint(5, size=(2,4))) #5미만
print(np.random.randint(5, 10,size=(2,4))) #5이상 10미만
print(np.random.rand(2, 3)) #5이상 10미만

[[4 2 2 2]
 [2 0 4 3]]
[[9 5 8 7]
 [5 9 6 8]]
[[0.36442684 0.99815486 0.85680798]
 [0.87413668 0.04916718 0.27471521]]


In [177]:
rng=np.random.default_rng()

In [189]:
# 정규분포를 따르는 랜덤함수
print(rng.random())
print(rng.integers(0,10,5))

0.04732308585438838
[1 0 4 4 7]


In [218]:
k=a>4
print(k)
print(k[0])
print(k[0][2])

[[False False  True]
 [False  True  True]]
[False False  True]
True


In [208]:
a[a>4]

array([5, 5, 6])